BiblioHarryv1/Models/Note.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace BiblioHarryv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public System.Guid NoteID { get; set; }
        [Required]
        [RegularExpression(@"^([\S\s]{4,})$", ErrorMessage = "Text must be entered, and must be at least 3 characters")]
        public string NoteList { get; set; }
        public string Palindrome { get; set; }
        public string Duplicates { get; set; }
        public System.DateTime EntryDate { get; set; }
    }
}

BiblioHarryv1/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BiblioHarryv1.Models;
using System.Text;

namespace BiblioHarryv1.Controllers
{
    public class NotesController : Controller
    {
        private BiblioNotesEntities db = new BiblioNotesEntities();

        // GET: /Notes/
        public ActionResult Index()
        {
            return View(db.Notes.ToList());
        }

        // GET: /Notes/Details/5
        public ActionResult Details(Guid? id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }


        //GET
        public ActionResult ShowDuplicates(string origkey)
        {
            if (origkey != "")
            {
                string[] ArrList = origkey.Split(new string[] { "\n", "\r\n" }, StringSplitOptions.RemoveEmptyEntries);
                int ListCount = ArrList.Length;
                StringBuilder DupList = new StringBuilder();

                if (ListCount > 0)
                {
                    DupList.Clear();
                    Array.Sort(ArrList);
                    for (int i = 1; i <= ListCount - 1; i++)
                    {
                        //check for duplicate
                        if (ArrList[i] == ArrList[i - 1])
                        {
                            DupList.AppendLine(ArrList[i]);
                        }
                    }
                }
                ViewBag.DupKeyword = DupList.ToString().Replace("\n", "<br />").Replace("\r", null);
                ViewBag.RawKeyword = DupList.ToString();
            }            
            return View();
        }

        // GET: /Notes/Create
        public ActionResult Create()
        {          

            return View();
        }

        //function to reverse string
        public string ReverseString (string inputString)
        {            
            char[] arrString = inputString.ToCharArray();
            Array.Reverse(arrString);
            string outString = new string(arrString);
            return outString;
        }

        public ActionResult SaveFile(string sText)
        {
            string filename = "bibliotheca" + System.DateTime.Now;
            Response.Clear();
            Response.ContentType = "text/html";
            Response.AddHeader("content-disposition", "attachment; filename=\"" + filename +".txt\"");
            Response.Write(sText);
            Response.End();
            return View();
        }
        // POST: /Notes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /*public ActionResult Create(FormCollection form)
         string temptext = "";
            temptext = form["notetext"].ToString();
         */

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Note model)
        {
            string temptext = "";
            if (ModelState.IsValid)
            {
                temptext = model.NoteList;
                string[] ArrList = temptext.Split(new string[] { "\n", "\r\n" }, StringSplitOptions.RemoveEmptyEntries);
                int ListCount = ArrList.Length;
                string sPalin = "";
                StringBuilder PalinList = new StringBuilder();

                if (ListCount > 0)
                {
                    PalinList.Clear();

                    for (int i = 0; i < ListCount; i++)
                    {
                        sPalin = ReverseString(ArrList[i]);
                        //check for palin
                        if (sPalin == ArrList[i])
                        {
                            PalinList.AppendLine(sPalin);
                        }
                    }
                }
                ViewBag.RawPalin = PalinList.ToString();
                ViewBag.Palintext = PalinList.ToString().Replace("\n", "<br />").Replace("\r", null);
                ViewBag.OrigKeyword = temptext;
            }

            return View(model);
        }

        // GET: /Notes/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // POST: /Notes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="NoteID,NoteList,Palindrome,Duplicates,EntryDate")] Note note)
        {
            if (ModelState.IsValid)
            {
                db.Entry(note).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(note);
        }

        // GET: /Notes/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // POST: /Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Note note = db.Notes.Find(id);
            db.Notes.Remove(note);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BiblioHarryv1/Views/Notes/Create.cshtml
@model BiblioHarryv1.Models.Note

@{
    ViewBag.Title = "Bibliotheca Notepad System";    
    var sPalin = "";
    var sRawPalin = (string)ViewBag.RawPalin;
    sPalin = (string)@ViewBag.Palintext == null ? "" : (string)@ViewBag.Palintext;
    var origKeyword = "";
    origKeyword = (string)@ViewBag.OrigKeyword == null ? "" : (string)@ViewBag.OrigKeyword;
}

<h2>Enter Keywords</h2>


@using (@Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
      
        <div class="form-group">
            @Html.LabelFor(model => model.NoteList, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.NoteList)
                @Html.ValidationMessageFor(model => model.NoteList)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
            <div class="col-md-offset-2 col-md-10">
                @if (origKeyword != "")
                { 
                      @Html.ActionLink("Display Duplicates", "ShowDuplicates", "Notes", new { origkey = origKeyword }, null)
               }
            </div>
        </div>
    </div>
    
    <table class="table">
    <tr>
        <th>
            <label id="palinlist">Palindromes List</label>
        </th>
        </tr>
    
    <tr>
        <th>
            <div class="form-group">
                <div class="col-md-10">
                    @Html.Raw(HttpUtility.HtmlDecode(sPalin))
                    @Html.Hidden("hiddenPalin", sRawPalin)
                    
                </div>
            </div>
            
        </th>
        <th>    
@if (sPalin != "")
{
     @Html.ActionLink("Save to file", "SaveFile", "Notes", new { sText = sRawPalin }, null)
}                     

        </th>
        </tr>
        </table> }

<div>
    @Html.ActionLink("Back to List", "Create")
</div>


        @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

BiblioHarryv1/Views/Notes/Delete.cshtml
@model BiblioHarryv1.Models.Note

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Note</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NoteList)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoteList)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Palindrome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Palindrome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duplicates)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duplicates)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EntryDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EntryDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BiblioHarryv1/Views/Notes/Details.cshtml
@model BiblioHarryv1.Models.Note

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Note</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NoteList)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoteList)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Palindrome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Palindrome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duplicates)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duplicates)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EntryDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EntryDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.NoteID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BiblioHarryv1/Views/Notes/Edit.cshtml
@model BiblioHarryv1.Models.Note

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Note</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.NoteID)

        <div class="form-group">
            @Html.LabelFor(model => model.NoteList, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoteList)
                @Html.ValidationMessageFor(model => model.NoteList)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Palindrome, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Palindrome)
                @Html.ValidationMessageFor(model => model.Palindrome)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duplicates, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duplicates)
                @Html.ValidationMessageFor(model => model.Duplicates)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EntryDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EntryDate)
                @Html.ValidationMessageFor(model => model.EntryDate)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BiblioHarryv1/Views/Notes/Index.cshtml
@model IEnumerable<BiblioHarryv1.Models.Note>

@{
    ViewBag.Title = "Bibliotheca Notepad";
}

<h2>Index</h2>
<p>
    @Html.ActionLink("Create List", "Create")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NoteList)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Palindrome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Duplicates)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EntryDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NoteList)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Palindrome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Duplicates)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EntryDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.NoteID }) |
            @Html.ActionLink("Details", "Details", new { id=item.NoteID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.NoteID })
        </td>
    </tr>
}

</table>

BiblioHarryv1/Views/Notes/ShowDuplicates.cshtml
@model BiblioHarryv1.Models.Note

@{
    ViewBag.Title = "ShowDuplicates";
    var skeyword = (string)ViewBag.DupKeyword;
    var rawkey = (string)ViewBag.RawKeyword;
}

<h2>Duplicates found in keyword</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <table class="table">
    <tr>
        <th>
            <label id="palinlist">Duplicate List</label>
        </th>
        </tr>
    
    <tr>
        <th>
            <div class="form-group">
                <div class="col-md-10">
                    @Html.Raw(HttpUtility.HtmlDecode(skeyword))
                    @Html.Hidden("rawkey", rawkey)
                    
                </div>
            </div>
            
        </th>
        <th>    
@if (skeyword != "")
{
     @Html.ActionLink("Save to file", "SaveFile", "Notes", new { sText = rawkey }, null)
}                     

        </th>
        </tr>
        </table> }

<div>
    @Html.ActionLink("Back to List", "Create")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}